version: 2.1
orbs:
    node: circleci/node@12.18.4
jobs:
    install:
        docker:
            - image: "cimg/base:stable"
        steps:
            - checkout
            - node/install
                install-npm: false
                install-yarn: true
            - node/test
                pkg-manager: yarn
                run-command: test:coverage
            - store_artifacts:
                path: coverage
workflows:
    node-tests:
        jobs:
            - coverage
