version: 2.1
orbs:
    node: circleci/node@4.2.0
jobs:
    install:
        working_directory: ~/pterodactyl-sdk
        executor:
            name: node/default
            tag: "12.18.4"
        steps:
            - checkout
            - node/install:
                install-npm: false
                install-yarn: true
            - node/install-packages:
                app-dir: ~/pterodactyl-sdk
                cache-path: node_modules
                pkg-manager: yarn
                override-ci-command: yarn install --frozen-lockfile --dev
            - persist_to_workspace:
                root: .
                paths:
                    - .
    coverage:
        executor:
            name: node/default
            tag: "12.18.4"
        steps:
            - attach_workspace:
                at: .
            - run:
                name: "Run Jest and Collect Coverage Reports"
                command: yarn test:coverage
            - store_artifacts:
                path: coverage
workflows:
    coverage:
        jobs:
            - install
            - coverage:
                context:
                    - Pterodactyl-sdk test
                requires:
                    - install
