version: 2.1
orbs:
    node: circleci/node@4.2.0
jobs:
    install:
        executor:
            name: node/default
            tag: "12.18.4"
        steps:
            - checkout
            - node/install:
                install-npm: false
                install-yarn: true
            - node/install-packages:
                pkg-manager: yarn
    coverage:
        executor:
            name: node/default
            tag: "12.18.4"
        steps:
            - checkout
            - run:
                name: "Run Jest and Collect Coverage Reports"
                command: yarn test:coverage
            - store_artifacts:
                path: coverage
workflows:
    coverage:
        jobs:
            - install
            - coverage
